# Generated by Django 2.0.6 on 2019-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('realName', models.CharField(max_length=100)),
                ('accountNumber', models.IntegerField(max_length=15)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
